In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"D:\ML\tmdbdf.csv")
df

,Unnamed: 0,index,id,title,overview,keywords,genres,poster_path
0,0,0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","rescue,mission,dream,airplane,paris,france,vir...","Action,ScienceFiction,Adventure",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
1,1,1,157336,Interstellar,The adventures of a group of explorers who mak...,"rescue,future,spacecraft,raceagainsttime,artif...","Adventure,Drama,ScienceFiction",/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg
2,2,2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"joker,sadism,chaos,secretidentity,crimefighter...","Drama,Action,Crime,Thriller",/qJ2tW6WMUDux911r6m7haRef0WH.jpg
3,3,3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","future,society,cultureclash,spacetravel,spacew...","Action,Adventure,Fantasy,ScienceFiction",/kyeqWdyUXW608qlYkRqosgbbJyK.jpg
4,4,4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"newyorkcity,superhero,shield,basedoncomic,alie...","ScienceFiction,Action,Adventure",/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg
...,...,...,...,...,...,...,...,...
20995,21067,21067,55758,Midnight FM,Popular TV anchorwoman & late night DJ Ko Sun-...,"radiostation,radio","Thriller,Crime,Action",/8WqtunxSTVFiyBAUYSXbTSh0Vc5.jpg
20996,21068,21068,79990,Desi Boyz,"Two friends lose their jobs, then part bitterl...",NaN,"Comedy,Drama",/2Tga4SJQTKSENOISM5CRIb240LR.jpg
20997,21069,21069,1030419,Legend of the Galactic Heroes: Die Neue These ...,The story focuses on the exploits of rivals Re...,"spacewar,spaceopera,military",Animation,/brrgSFtcymZWaXl5a23GJRWdOSY.jpg
20998,21070,21070,24080,You Stupid Man,An actress dumps her boyfriend when she gets a...,"lovetriangle,director,break-up,ex-boyfriendex-...","Comedy,Romance",/vNfx5MBXkeqZKOW6Wx9W5kiNdSL.jpg
20999,21071,21071,1363,The Hi-Lo Country,An intimate story of the enduring bond of frie...,"pearlharbor,cowboy,pickuptruck,horseridingacci...","Drama,Romance,Western",/m73KqOLXf9ZvPVCWS5dz5Hv7yQF.jpg

In [3]:
df.shape

(21000, 8)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21000 entries, 0 to 20999
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   21000 non-null  int64
 1   index        21000 non-null  int64
 2   id           21000 non-null  int64
 3   title        21000 non-null  object
 4   overview     21000 non-null  object
 5   keywords     18535 non-null  object
 6   genres       20993 non-null  object
 7   poster_path  21000 non-null  object
dtypes: int64(3), object(5)
memory usage: 1.3+ MB

In [5]:
df.duplicated().sum()

0

In [6]:
df.isna().sum()

Unnamed: 0        0
index             0
id                0
title             0
overview          0
keywords       2465
genres            7
poster_path       0
dtype: int64

In [7]:
df.drop(columns=['Unnamed: 0','index'],inplace=True)

In [8]:
df

,id,title,overview,keywords,genres,poster_path
0,27205,Inception,"Cobb, a skilled thief who commits corporate es...","rescue,mission,dream,airplane,paris,france,vir...","Action,ScienceFiction,Adventure",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
1,157336,Interstellar,The adventures of a group of explorers who mak...,"rescue,future,spacecraft,raceagainsttime,artif...","Adventure,Drama,ScienceFiction",/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg
2,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,"joker,sadism,chaos,secretidentity,crimefighter...","Drama,Action,Crime,Thriller",/qJ2tW6WMUDux911r6m7haRef0WH.jpg
3,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","future,society,cultureclash,spacetravel,spacew...","Action,Adventure,Fantasy,ScienceFiction",/kyeqWdyUXW608qlYkRqosgbbJyK.jpg
4,24428,The Avengers,When an unexpected enemy emerges and threatens...,"newyorkcity,superhero,shield,basedoncomic,alie...","ScienceFiction,Action,Adventure",/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg
...,...,...,...,...,...,...
20995,55758,Midnight FM,Popular TV anchorwoman & late night DJ Ko Sun-...,"radiostation,radio","Thriller,Crime,Action",/8WqtunxSTVFiyBAUYSXbTSh0Vc5.jpg
20996,79990,Desi Boyz,"Two friends lose their jobs, then part bitterl...",NaN,"Comedy,Drama",/2Tga4SJQTKSENOISM5CRIb240LR.jpg
20997,1030419,Legend of the Galactic Heroes: Die Neue These ...,The story focuses on the exploits of rivals Re...,"spacewar,spaceopera,military",Animation,/brrgSFtcymZWaXl5a23GJRWdOSY.jpg
20998,24080,You Stupid Man,An actress dumps her boyfriend when she gets a...,"lovetriangle,director,break-up,ex-boyfriendex-...","Comedy,Romance",/vNfx5MBXkeqZKOW6Wx9W5kiNdSL.jpg
20999,1363,The Hi-Lo Country,An intimate story of the enduring bond of frie...,"pearlharbor,cowboy,pickuptruck,horseridingacci...","Drama,Romance,Western",/m73KqOLXf9ZvPVCWS5dz5Hv7yQF.jpg

In [9]:
df.describe(include="all")

,id,title,overview,keywords,genres,poster_path
count,2.100000e+04,21000,21000,18535,20993,21000
unique,NaN,19934,20993,17678,3306,21000
top,NaN,The Return,Wilbur the pig is scared of the end of the sea...,womandirector,Comedy,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
freq,NaN,6,2,111,1647,1
mean,2.065386e+05,NaN,NaN,NaN,NaN,NaN
std,2.607422e+05,NaN,NaN,NaN,NaN,NaN
min,2.000000e+00,NaN,NaN,NaN,NaN,NaN
25%,1.391975e+04,NaN,NaN,NaN,NaN,NaN
50%,4.906750e+04,NaN,NaN,NaN,NaN,NaN
75%,3.762400e+05,NaN,NaN,NaN,NaN,NaN
max,1.181678e+06,NaN,NaN,NaN,NaN,NaN

In [10]:
df.describe(include='object')

,title,overview,keywords,genres,poster_path
count,21000,21000,18535,20993,21000
unique,19934,20993,17678,3306,21000
top,The Return,Wilbur the pig is scared of the end of the sea...,womandirector,Comedy,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg
freq,6,2,111,1647,1

In [11]:
df['tags'] = df['overview'] + df['keywords'] + df['genres']

In [12]:
df['tags']

0        Cobb, a skilled thief who commits corporate es...
1        The adventures of a group of explorers who mak...
2        Batman raises the stakes in his war on crime. ...
3        In the 22nd century, a paraplegic Marine is di...
4        When an unexpected enemy emerges and threatens...
                               ...
20995    Popular TV anchorwoman & late night DJ Ko Sun-...
20996                                                  NaN
20997    The story focuses on the exploits of rivals Re...
20998    An actress dumps her boyfriend when she gets a...
20999    An intimate story of the enduring bond of frie...
Name: tags, Length: 21000, dtype: object

In [13]:
df.isna().sum()

id                0
title             0
overview          0
keywords       2465
genres            7
poster_path       0
tags           2468
dtype: int64

In [14]:
df['tags'] = df['overview'] + df['keywords'].fillna('') + df['genres'].fillna('')

In [15]:
df.isna().sum()

id                0
title             0
overview          0
keywords       2465
genres            7
poster_path       0
tags              0
dtype: int64

# Text Preprocessing

In [16]:
df['tags'] = df['tags'].apply(lambda x:x.lower())

In [17]:
df['tags']

0        cobb, a skilled thief who commits corporate es...
1        the adventures of a group of explorers who mak...
2        batman raises the stakes in his war on crime. ...
3        in the 22nd century, a paraplegic marine is di...
4        when an unexpected enemy emerges and threatens...
                               ...
20995    popular tv anchorwoman & late night dj ko sun-...
20996    two friends lose their jobs, then part bitterl...
20997    the story focuses on the exploits of rivals re...
20998    an actress dumps her boyfriend when she gets a...
20999    an intimate story of the enduring bond of frie...
Name: tags, Length: 21000, dtype: object

# pip install nltk

In [20]:
from nltk.stem.porter import PorterStemmer

In [21]:
ps = PorterStemmer()

In [22]:
def stemming(word):
    y = []
    for i in word.split():
        y.append(ps.stem(i))
    return ' '.join(y)

In [23]:
df['tags'].iloc[0]

'cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.rescue,mission,dream,airplane,paris,france,virtualreality,kidnapping,philosophy,spy,allegory,manipulation,carcrash,heist,memory,architecture,losangeles,california,dreamworld,subconsciousaction,sciencefiction,adventure'

In [24]:
df['tags'] = df['tags'].apply(stemming)

In [25]:
df['tags'].iloc[0]

'cobb, a skill thief who commit corpor espionag by infiltr the subconsci of hi target is offer a chanc to regain hi old life as payment for a task consid to be impossible: "inception", the implant of anoth person\' idea into a target\' subconscious.rescue,mission,dream,airplane,paris,france,virtualreality,kidnapping,philosophy,spy,allegory,manipulation,carcrash,heist,memory,architecture,losangeles,california,dreamworld,subconsciousaction,sciencefiction,adventur'

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [27]:
cv = CountVectorizer(max_features=10000,stop_words='english')

In [28]:
vector = cv.fit_transform(df['tags'])

In [29]:
vector.shape

(21000, 10000)

In [30]:
cv.get_feature_names_out().tolist()

['000',
 '10',
 '100',
 '10th',
 '11',
 '12',
 '12th',
 '12thcentury',
 '13',
 '13th',
 '13thcentury',
 '14',
 '1453',
 '14th',
 '15',
 '150',
 '15th',
 '15thcentury',
 '16',
 '16th',
 '16thcentury',
 '17',
 '17th',
 '17thcentury',
 '17thcenturydrama',
 '18',
 '1890',
 '18th',
 '18thcentury',
 '19',
 '1900',
 '1900s',
 '1900sdrama',
 '1910s',
 '1910sdrama',
 '1917',
 '1918',
 '1920',
 '1920s',
 '1920sdrama',
 '1930',
 '1930s',
 '1930scomedy',
 '1930sdrama',
 '1931',
 '1936',
 '1937',
 '1938',
 '1939',
 '1940',
 '1940s',
 '1940sdrama',
 '1940swar',
 '1941',
 '1942',
 '1943',
 '1944',
 '1945',
 '1950',
 '1950s',
 '1950scomedy',
 '1950sdrama',
 '1954',
 '1955',
 '1956',
 '1957',
 '1958',
 '1959',
 '1960',
 '1960s',
 '1960sdrama',
 '1961',
 '1962',
 '1963',
 '1964',
 '1965',
 '1966',
 '1967',
 '1968',
 '1969',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1980s',
 '1980sdrama',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1990s',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '19th',
 '19thcentury',
 '19thcenturyadventure',
 '19thcenturydrama',
 '19thcenturywestern',
 '1stcentury',
 '20',
 '200',
 '2000',
 '2000s',
 '2001',
 '2002',
 '2003',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2040s',
 '20th',
 '21',
 '21st',
 '22',
 '22nd',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '300',
 '30s',
 '30th',
 '31',
 '35',
 '37',
 '39',
 '3d',
 '40',
 '400',
 '45',
 '47',
 '476',
 '48',
 '50',
 '500',
 '51',
 '60',
 '60s',
 '62',
 '70',
 '70s',
 '7th',
 '80',
 '80s',
 '90',
 '90s',
 '95',
 'aaron',
 'abandon',
 'abandoned',
 'abandonedhouse',
 'abandonment',
 'abbi',
 'abby',
 'abduct',
 'abduction',
 'abe',
 'abel',
 'abid',
 'abigail',
 'abil',
 'abilities',
 'abl',
 'aboard',
 'aborigin',
 'abort',
 'abortion',
 'abound',
 'abov',
 'abraham',
 'abroad',
 'abrupt',
 'abruptli',
 'absenc',
 'absence',
 'absent',
 'absolut',
 'absorb',
 'absurd',
 'abus',
 'abuse',
 'abusivefather',
 'abusivehusband',
 'abyss',
 'academ',
 'academi',
 'academy',
 'acapulco',
 'accept',
 'access',
 'accid',
 'accident',
 'accidentaldeath',
 'accidents',
 'acclaim',
 'accompani',
 'accomplic',
 'accomplish',
 'accord',
 'account',
 'accountant',
 'accus',
 'ace',
 'achiev',
 'acid',
 'acquaint',
 'acquir',
 'acr',
 'act',
 'action',
 'actionhero',
 'actionheroaction',
 'actions',
 'activ',
 'activism',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'actual',
 'ad',
 'adam',
 'adams',
 'adapt',
 'add',
 'addict',
 'addiction',
 'addit',
 'addl',
 'address',
 'adjust',
 'administ',
 'administr',
 'admir',
 'admit',
 'adolesc',
 'adolescence',
 'adolf',
 'adolfhitler',
 'adopt',
 'adoptedchild',
 'adoption',
 'adoptivefather',
 'ador',
 'adrenaline',
 'adrien',
 'adrift',
 'adult',
 'adultanimation',
 'adultanimationanimation',
 'adulter',
 'adultery',
 'adulthood',
 'adults',
 'advanc',
 'advantag',
 'advantage',
 'adventur',
 'adventure',
 'adventurer',
 'adventures',
 'adversari',
 'adversary',
 'advertis',
 'advertising',
 'advertisingagency',
 'advertisingexecutive',
 'advic',
 'advice',
 'advis',
 'advisor',
 'affair',
 'affairs',
 'affect',
 'affection',
 'affections',
 'afflict',
 'affluent',
 'afford',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'aft',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'afternoon',
 'ag',
 'agatha',
 'age',
 'agedifference',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'aggression',
 'aggressive',
 'aging',
 'agn',
 'ago',
 'agoraphobia',
 'agre',
 'agreement',
 'agrees',
 'ah',
 'ahead',
 'aid',
 'aids',
 'ail',
 'aim',
 'aimless',
 'air',
 'aircraft',
 'aires',
 'airforce',
 'airlin',
 'airplan',
 'airplane',
 'airplanecrash',
 'airplanehijacking',
 'airport',
 'aka',
 'akan',
 'al',
 'alabama',
 'aladdin',
 'alain',
 'alan',
 'alarm',
 'alaska',
 'alaskan',
 'albanian',
 'albeit',
 'albert',
 'alberto',
 'album',
 'alchemist',
 'alcohol',
 'alcoholabuse',
 'alcoholic',
 'alcoholism',
 'aldo',
 'alec',
 'alejandro',
 'alert',
 'alessandro',
 'alex',
 'alexand',
 'alexander',
 'alexandr',
 'alexandra',
 'alfr',
 'alfredo',
 'algeria',
 'algerian',
 'ali',
 'alibi',
 'alic',
 'alice',
 'alicia',
 'alien',
 'alienabduction',
 'alienation',
 'alieninfection',
 'alieninvasion',
 'alieninvasionsciencefiction',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'alike',
 'aliv',
 'alive',
 'allan',
 'alleg',
 'allegedli',
 'allegi',
 'allegory',
 'allen',
 'alley',
 'alli',
 'allianc',
 'allies',
 'alligator',
 'allison',
 'allow',
 'allur',
 'ally',
 'alma',
 'alon',
 'alongsid',
 'alp',
 'alpha',
 'alps',
 'alpsmountains',
 'alreadi',
 'alt',
 'altar',
 'alter',
 'alterego',
 'altern',
 'alternatedimension',
 'alternatehistory',
 'alternatereality',
 'alternatetimeline',
 'alvin',
 'alway',
 'alzheimer',
 'amaia',
 'amanda',
 'amateur',
 'amateurdetective',
 'amaz',
 'amazon',
 'amazonrainforest',
 'ambassador',
 'amber',
 'ambigu',
 'ambit',
 'ambiti',
 'ambition',
 'ambitions',
 'ambul',
 'ambulance',
 'ambush',
 'amelia',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americandream',
 'americanfootball',
 'americans',
 'ami',
 'amid',
 'amidst',
 'amish',
 'amnesia',
 'amnesiac',
 'amor',
 'amp',
 'amputation',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'ana',
 'anaconda',
 'analyst',
 'analyz',
 'anarchiccomedycomedi',
 'anarchiccomedycomedy',
 'anarchist',
 'ancestor',
 'ancestr',
 'anchor',
 'ancient',
 'ancientegypt',
 'ancientgreece',
 'ancientrome',
 'ancientworld',
 'anderson',
 'andi',
 'andrea',
 'andrew',
 'android',
 'andré',
 'andy',
 'anew',
 'angel',
 'angela',
 'angeles',
 'anger',
 'angi',
 'angri',
 'angst',
 'ani',
 'anim',
 'animal',
 'animalattack',
 'animalhorror',
 'animalhorrorhorror',
 'animals',
 'animatedscene',
 'animation',
 'anime',
 'animeaction',
 'animeadventure',
 'animeanimation',
 'animefamily',
 'ann',
 'anna',
 'annabel',
 'anne',
 'anni',
 'annie',
 'anniversari',
 'anniversary',
 'announc',
 'annoy',
 'annual',
 'anonym',
 'anonymousletter',
 'anorexia',
 'anoth',
 'answer',
 'answers',
 'ant',
 'antarctica',
 'antholog',
 'anthology',
 'anthoni',
 'anthropologist',
 'anthropology',
 'anthropomorphism',
 'anti',
 'antic',
 'anticip',
 'antics',
 'antidote',
 'antihero',
 'antiqu',
 'antiwar',
 'antoin',
 'antoine',
 'anton',
 'antonia',
 'antonio',
 'antwerp',
 'anxieti',
 'anxiety',
 'anxiou',
 'anxious',
 'anybodi',
 'anymore',
 'anyon',
 'anyth',
 'apach',
 'apachenation',
 'apart',
 'apartheid',
 'apartment',
 'apartmentbuilding',
 'apartments',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'apocalypticfuture',
 'apollo',
 'app',
 'appar',
 'apparit',
 'apparition',
 'appeal',
 'appear',
 'appearance',
 'appears',
 'appl',
 'apple',
 'appli',
 'appoint',
 'appreci',
 'apprehend',
 'apprentic',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'approv',
 'april',
 'aquarium',
 'aquat',
 'ar',
 'arab',
 'arabian',
 'arabiannights',
 'arbitrarylaw',
 'arch',
 'archaeologist',
 'archeology',
 'archer',
 'architect',
 'architecture',
 'archiv',
 'arctic',
 'arcticpolarcircleregion',
 'arduou',
 'area',
 'aren',
 'arena',
 'argentina',
 'argentinian',
 'argu',
 'argument',
 'ariel',
 'aris',
 'aristocrat',
 'arizona',
 'ark',
 'arkansa',
 'arkansas',
 'arm',
 'armageddon',
 'armando',
 'armi',
 'armor',
 'arms',
 'armsdealer',
 'armstrong',
 'army',
 'arnaud',
 'arnold',
 'arrang',
 'arrangedmarriage',
 'array',
 'arrest',
 'arrested',
 'arriv',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'arrog',
 'arrogance',
 'arrogant',
 'arrow',
 'arson',
 'art',
 'artagnan',
 'artgallery',
 'arthur',
 'articl',
 'artifact',
 'artifici',
 'artificialintelligence',
 'artist',
 'artists',
 'arts',
 'artthief',
 'arturo',
 'ascend',
 'asgard',
 'ash',
 'ashes',
 'ashley',
 'asia',
 'asian',
 'asid',
 'ask',
 'asleep',
 'aspect',
 'asperger',
 'aspir',
 'aspiringactor',
 'aspiringwriter',
 'assail',
 'assassin',
 'assassination',
 'assassinationattempt',
 'assassins',
 'assault',
 'assembl',
 'asset',
 'assign',
 'assignment',
 'assist',
 'assistant',
 'associ',
 'assort',
 'assum',
 'assur',
 'asterix',
 'asteroid',
 'astonish',
 'astronaut',
 'astronom',
 'astronomer',
 'asylum',
 'atheist',
 'athena',
 'athlet',
 'atlant',
 'atlanta',
 'atlanticocean',
 'atmospher',
 'atom',
 'atomicbomb',
 'attach',
 'attack',
 'attacks',
 'attain',
 'attempt',
 'attemptedmurder',
 'attemptedrape',
 'attempttoescape',
 'attend',
 'attent',
 'attention',
 'attic',
 'attitud',
 'attitude',
 'attorney',
 'attract',
 'attraction',
 'attractive',
 'auction',
 'audaci',
 'audienc',
 'audience',
 'audit',
 'audition',
 'audrey',
 'august',
 'aunt',
 'aurora',
 'auschwitz',
 'austin',
 'australia',
 'australian',
 'australianoutback',
 'austria',
 'austrian',
 'author',
 'authorities',
 'authority',
 'autism',
 'autist',
 'auto',
 'autobiograph',
 'autobiography',
 'autobot',
 'automobil',
 'autopsy',
 'autumn',
 'ava',
 'avail',
 'avalanche',
 'avant',
 'aveng',
 'avenu',
 'averag',
 'aviat',
 'aviation',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awesom',
 'awkward',
 'awri',
 'awry',
 'ax',
 'axe',
 'axel',
 'axemurder',
 'babe',
 'babi',
 'babies',
 'baby',
 'babysit',
 'babysitt',
 'babysitter',
 'bachelor',
 'bachelorett',
 'backdrop',
 'backfir',
 'backfromthedead',
 'background',
 'backpack',
 'backstag',
 'backward',
 'backwat',
 'backwood',
 'backyard',
 'bad',
 'badli',
 'badluck',
 'badmother',
 'baffl',
 'bag',
 'bagofmoney',
 'bahamas',
 'bail',
 'bailey',
 'baker',
 'bakery',
 'balanc',
 'balance',
 'ball',
 'ballerina',
 'ballet',
 'balletdancer',
 'balloon',
 'balthazar',
 'baltimor',
 'baltimore',
 'ban',
 'banana',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankheist',
 'bankmanager',
 'bankrobber',
 'bankrobbery',
 'bankrupt',
 'bankruptcy',
 'banner',
 'baptism',
 'bar',
 'barb',
 'barbara',
 'barbarian',
 'barber',
 'barbershop',
 'barbi',
 'barbie',
 'barcelona',
 'bare',
 'bareknuckleboxing',
 'barfight',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barren',
 'barri',
 'barricad',
 'barrier',
 'barry',
 'bars',
 'bart',
 'bartend',
 'bartender',
 'bas',
 'base',
 'basebal',
 'baseball',
 'baseballbat',
 'basedonanime',
 'basedoncartoon',
 'basedonchildren',
 'basedoncomic',
 'basedonfairytale',
 'basedongraphicnovel',
 'basedonmagazine',
 'basedonmanga',
 'basedonmemoirorautobiography',
 'basedonmovie',
 'basedonmyths',
 'basedonnovelorbook',
 'basedonplayormusical',
 'basedonshortfilm',
 'basedonshortstory',
 'basedonsong',
 'basedontoy',
 'basedontoyanimation',
 'basedontruestory',
 'basedontruestorydrama',
 'basedontvseries',
 'basedontvseriesaction',
 'basedontvseriesanimation',
 'basedontvseriescomedy',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basedonyoungadultnoveladventure',
 'basedonyoungadultnovelcomedy',
 'basedonyoungadultnoveldrama',
 'basedonyoungadultnovelfantasy',
 'basement',
 'basi',
 'basic',
 'basketbal',
 'basketball',
 'basqu',
 'bat',
 'bath',
 'bathroom',
 'bathtub',
 'batman',
 'battalion',
 'battl',
 'battle',
 'battlefield',
 'battleforpower',
 'battleship',
 'bavaria',
 'bay',
 'bayou',
 'bdsm',
 'bea',
 'beach',
 'beachhouse',
 'bean',
 'bear',
 'beard',
 'beast',
 'beasts',
 'beat',
 'beaten',
 'beating',
 'beatric',
 'beatrice',
 'beau',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'beautysalon',
 'becam',
 'becaus',
 'beck',
 'beckett',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'bee',
 'beer',
 'beethoven',
 'befal',
 'befor',
 'befriend',
 'beg',
 'began',
 'beggar',
 'begin',
 'beginning',
 'begins',
 'begun',
 'behalf',
 'behav',
 'behavior',
 'behaviour',
 'beheading',
 'behindenemylines',
 'behindthescenes',
 'beij',
 'beijing',
 'beings',
 'belfast',
 'belgian',
 'belgium',
 'belief',
 'beliefs',
 'believ',
 'believe',
 'bell',
 'bella',
 'belle',
 'belong',
 ...]

# Calculate Similarity Score

In [31]:
from sklearn.metrics.pairwise import cosine_similarity

In [32]:
similarity = cosine_similarity(vector)

In [33]:
similarity[0]

array([1.        , 0.06454972, 0.03526728, ..., 0.        , 0.06154575,
       0.        ])

In [34]:
similaritydf = pd.DataFrame(similarity,index=df['title'],columns=df['title'])

In [35]:
similaritydf

title,Inception,Interstellar,The Dark Knight,Avatar,The Avengers,Deadpool,Avengers: Infinity War,Fight Club,Guardians of the Galaxy,Pulp Fiction,...,Manufacturing Consent: Noam Chomsky and the Media,The Desert Rats,WeWork: or The Making and Breaking of a $47 Billion Unicorn,RKO 281,The Jackpot!,Midnight FM,Desi Boyz,Legend of the Galactic Heroes: Die Neue These - Intrigue 1,You Stupid Man,The Hi-Lo Country
title,,,,,,,,,,,,,,,,,,,,,
Inception,1.000000,0.064550,0.035267,0.023729,0.047458,0.111359,0.072169,0.000000,0.113228,0.115563,...,0.090289,0.038576,0.038576,0.057735,0.144338,0.000000,0.000000,0.000000,0.061546,0.000000
Interstellar,0.064550,1.000000,0.000000,0.122536,0.024507,0.000000,0.074536,0.047741,0.146176,0.047741,...,0.000000,0.039841,0.039841,0.029814,0.000000,0.000000,0.056344,0.000000,0.031782,0.027217
The Dark Knight,0.035267,0.000000,1.000000,0.000000,0.080338,0.094256,0.091627,0.000000,0.047919,0.078251,...,0.025474,0.032651,0.032651,0.024434,0.048868,0.069264,0.000000,0.030542,0.026047,0.044610
Avatar,0.023729,0.122536,0.000000,1.000000,0.000000,0.025367,0.061650,0.000000,0.032241,0.000000,...,0.000000,0.043937,0.000000,0.000000,0.000000,0.031068,0.000000,0.041100,0.000000,0.030015
The Avengers,0.047458,0.024507,0.080338,0.000000,1.000000,0.076102,0.164399,0.000000,0.257930,0.026325,...,0.000000,0.021969,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.035050,0.030015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Midnight FM,0.000000,0.000000,0.069264,0.031068,0.000000,0.000000,0.000000,0.000000,0.000000,0.030261,...,0.000000,0.000000,0.000000,0.037796,0.037796,1.000000,0.000000,0.000000,0.040291,0.034503
Desi Boyz,0.000000,0.056344,0.000000,0.000000,0.000000,0.000000,0.000000,0.060523,0.000000,0.000000,...,0.000000,0.050508,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
Legend of the Galactic Heroes: Die Neue These - Intrigue 1,0.000000,0.000000,0.030542,0.041100,0.000000,0.038576,0.031250,0.000000,0.000000,0.040032,...,0.000000,0.000000,0.133631,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.045644
You Stupid Man,0.061546,0.031782,0.026047,0.000000,0.035050,0.065795,0.053300,0.034139,0.041812,0.068279,...,0.044455,0.028490,0.056980,0.042640,0.085280,0.040291,0.000000,0.000000,1.000000,0.000000
The Hi-Lo Country,0.000000,0.027217,0.044610,0.030015,0.030015,0.028172,0.022822,0.000000,0.000000,0.029235,...,0.038069,0.024398,0.048795,0.036515,0.000000,0.034503,0.000000,0.045644,0.000000,1.000000

In [36]:
similaritydf.loc['Avatar'].sort_values(ascending=False)[1:6]

title
Ikarie XB 1            0.273998
Skylines               0.250706
King Shakir Recycle    0.245072
Aliens in the Attic    0.227980
Independence Day       0.227836
Name: Avatar, dtype: float64

In [40]:
list(enumerate(similarity[0]))

[(0, 1.0000000000000007),
 (1, 0.06454972243679029),
 (2, 0.03526728079292992),
 (3, 0.023728949893812478),
 (4, 0.047457899787624956),
 (5, 0.11135885079684352),
 (6, 0.07216878364870323),
 (7, 0.0),
 (8, 0.11322770341445959),
 (9, 0.11556254088025608),
 (10, 0.09558988911273408),
 (11, 0.16829726687457877),
 (12, 0.058925565098878974),
 (13, 0.07216878364870322),
 (14, 0.1655665446331305),
 (15, 0.0220112726581406),
 (16, 0.0660338179744218),
 (17, 0.03187883565316692),
 (18, 0.0440225453162812),
 (19, 0.07273929674533079),
 (20, 0.0),
 (21, 0.04622501635210243),
 (22, 0.02254174086668581),
 (23, 0.04303314829119353),
 (24, 0.0),
 (25, 0.0),
 (26, 0.029462782549439487),
 (27, 0.11274690420042435),
 (28, 0.07777137710478191),
 (29, 0.048112522432468816),
 (30, 0.07580980435789034),
 (31, 0.03187883565316692),
 (32, 0.149071198499986),
 (33, 0.061858957413174195),
 (34, 0.031497039417435604),
 (35, 0.022821773229381927),
 (36, 0.0),
 (37, 0.023728949893812478),
 (38, 0.0),
 (39, 0.07647191129018727),
 (40, 0.16632478596477893),
 (41, 0.10879853497231115),
 (42, 0.052704627669472995),
 (43, 0.08505172717997148),
 (44, 0.02254174086668581),
 (45, 0.07715167498104597),
 (46, 0.03526728079292992),
 (47, 0.0),
 (48, 0.023112508176051216),
 (49, 0.0),
 (50, 0.0),
 (51, 0.18750000000000006),
 (52, 0.20328584951250755),
 (53, 0.10008009612817947),
 (54, 0.10640706634484359),
 (55, 0.13801311186847087),
 (56, 0.12309149097933274),
 (57, 0.033113308926626096),
 (58, 0.11895773785772164),
 (59, 0.0862581949177943),
 (60, 0.042562826537937436),
 (61, 0.11270870433342906),
 (62, 0.0220112726581406),
 (63, 0.0),
 (64, 0.0),
 (65, 0.0),
 (66, 0.15204091013988436),
 (67, 0.0),
 (68, 0.0),
 (69, 0.03402069087198859),
 (70, 0.05360562674188975),
 (71, 0.0652791209833867),
 (72, 0.0660338179744218),
 (73, 0.10825317547305484),
 (74, 0.023728949893812478),
 (75, 0.0),
 (76, 0.20309059861498086),
 (77, 0.018042195912175808),
 (78, 0.23764659394667925),
 (79, 0.12909944487358058),
 (80, 0.048795003647426664),
 (81, 0.0),
 (82, 0.06762522260005743),
 (83, 0.1965892748731962),
 (84, 0.13055824196677338),
 (85, 0.06299407883487121),
 (86, 0.036661778755338326),
 (87, 0.0),
 (88, 0.0),
 (89, 0.0),
 (90, 0.08164965809277261),
 (91, 0.06454972243679029),
 (92, 0.0),
 (93, 0.0),
 (94, 0.06933752452815364),
 (95, 0.0),
 (96, 0.0),
 (97, 0.0220112726581406),
 (98, 0.15753150945315111),
 (99, 0.05184758473652127),
 (100, 0.06250000000000001),
 (101, 0.06950480468569159),
 (102, 0.040824829046386304),
 (103, 0.046829290579084706),
 (104, 0.0),
 (105, 0.039652579285907215),
 (106, 0.04210759605332595),
 (107, 0.0),
 (108, 0.025923792368260635),
 (109, 0.05184758473652127),
 (110, 0.023728949893812478),
 (111, 0.09365858115816941),
 (112, 0.0),
 (113, 0.06933752452815364),
 (114, 0.021516574145596764),
 (115, 0.021281413268968718),
 (116, 0.06063390625908324),
 (117, 0.02083333333333334),
 (118, 0.06019292654288461),
 (119, 0.04303314829119353),
 (120, 0.0790569415042095),
 (121, 0.04564354645876385),
 (122, 0.02175970699446223),
 (123, 0.08171505630757667),
 (124, 0.0),
 (125, 0.08492077756084469),
 (126, 0.08505172717997148),
 (127, 0.11135885079684352),
 (128, 0.027777777777777783),
 (129, 0.0),
 (130, 0.0),
 (131, 0.13693063937629155),
 (132, 0.10825317547305485),
 (133, 0.11180339887498951),
 (134, 0.0),
 (135, 0.06299407883487121),
 (136, 0.020412414523193152),
 (137, 0.0739221270954573),
 (138, 0.0),
 (139, 0.17902871850985824),
 (140, 0.19364916731037088),
 (141, 0.08164965809277261),
 (142, 0.0),
 (143, 0.04123930494211613),
 (144, 0.0),
 (145, 0.09395575350035364),
 (146, 0.026802813370944874),
 (147, 0.0),
 (148, 0.038924947208076155),
 (149, 0.0),
 (150, 0.0),
 (151, 0.0),
 (152, 0.058925565098878974),
 (153, 0.08951435925492914),
 (154, 0.05838742081211423),
 (155, 0.0),
 (156, 0.07715167498104597),
 (157, 0.0),
 (158, 0.07856742013183862),
 (159, 0.1351474756798972),
 (160, 0.0),
 (161, 0.0),
 (162, 0.042562826537937436),
 (163, 0.04351941398892446),
 (164, 0.07118684968143743),
 (165, 0.07453559924999299),
 (166, 0.0),
 (167, 0.04166666666666668),
 (168, 0.015214515486254616),
 (169, 0.12729376930432887),
 (170, 0.04514469490716346),
 (171, 0.0),
 (172, 0.0),
 (173, 0.018480531773864325),
 (174, 0.0862581949177943),
 (175, 0.04003203845127179),
 (176, 0.020619652471058066),
 (177, 0.0),
 (178, 0.047457899787624956),
 (179, 0.0),
 (180, 0.07856742013183862),
 (181, 0.15101011242315548),
 (182, 0.08040844011283463),
 (183, 0.12247448713915891),
 (184, 0.02551551815399144),
 (185, 0.20721243174558496),
 (186, 0.0739221270954573),
 (187, 0.11322770341445959),
 (188, 0.0),
 (189, 0.0),
 (190, 0.04564354645876385),
 (191, 0.0909241209316635),
 (192, 0.19397004436111456),
 (193, 0.03696106354772865),
 (194, 0.05838742081211423),
 (195, 0.1137147065368355),
 (196, 0.0),
 (197, 0.11589658124319133),
 (198, 0.03823595564509363),
 (199, 0.019641855032959656),
 (200, 0.05006261743217589),
 (201, 0.047457899787624956),
 (202, 0.1636634176769943),
 (203, 0.05103103630798288),
 (204, 0.0),
 (205, 0.0),
 (206, 0.0),
 (207, 0.0),
 (208, 0.0),
 (209, 0.1047697595156187),
 (210, 0.0),
 (211, 0.07426106572325057),
 (212, 0.09622504486493763),
 (213, 0.017376201171422898),
 (214, 0.030949223029508647),
 (215, 0.0),
 (216, 0.10640706634484359),
 (217, 0.0),
 (218, 0.0),
 (219, 0.05499266813300749),
 (220, 0.11274690420042435),
 (221, 0.07216878364870323),
 (222, 0.019117977822546817),
 (223, 0.049507377148833714),
 (224, 0.04303314829119353),
 (225, 0.07580980435789034),
 (226, 0.05838742081211423),
 (227, 0.09016696346674324),
 (228, 0.0),
 (229, 0.0440225453162812),
 (230, 0.037267799624996496),
 (231, 0.02551551815399144),
 (232, 0.19462473604038077),
 (233, 0.023414645289542353),
 (234, 0.06454972243679029),
 (235, 0.08980265101338746),
 (236, 0.19127301391900148),
 (237, 0.10476975951561872),
 (238, 0.0),
 (239, 0.0),
 (240, 0.042562826537937436),
 (241, 0.15161960871578067),
 (242, 0.026802813370944874),
 (243, 0.03526728079292992),
 (244, 0.0),
 (245, 0.0),
 (246, 0.016239245061540775),
 (247, 0.04303314829119353),
 (248, 0.0),
 (249, 0.0),
 (250, 0.038924947208076155),
 (251, 0.024397501823713332),
 (252, 0.17902871850985827),
 (253, 0.1559023911155809),
 (254, 0.04564354645876385),
 (255, 0.08606629658238706),
 (256, 0.048112522432468816),
 (257, 0.09491579957524991),
 (258, 0.0),
 (259, 0.11909826683508273),
 (260, 0.10309826235529033),
 (261, 0.0652791209833867),
 (262, 0.147087101353638),
 (263, 0.12591385028629828),
 (264, 0.10067340828210367),
 (265, 0.0),
 (266, 0.12909944487358058),
 (267, 0.06454972243679029),
 (268, 0.11371470653683549),
 (269, 0.18330889377669163),
 (270, 0.05360562674188975),
 (271, 0.13608276348795437),
 (272, 0.0),
 (273, 0.14090046549415863),
 (274, 0.0220112726581406),
 (275, 0.09449111825230681),
 (276, 0.0),
 (277, 0.15294382258037453),
 (278, 0.025923792368260635),
 (279, 0.05685735326841775),
 (280, 0.0220112726581406),
 (281, 0.0),
 (282, 0.06454972243679029),
 (283, 0.0),
 (284, 0.0790569415042095),
 (285, 0.1276884796138123),
 (286, 0.056613851707229795),
 (287, 0.11322770341445959),
 (288, 0.0),
 (289, 0.10741723110591495),
 (290, 0.0),
 (291, 0.020211302086361082),
 (292, 0.12436708454077278),
 (293, 0.06384423980690615),
 (294, 0.06316139407998893),
 (295, 0.0),
 (296, 0.017503501050350125),
 (297, 0.05184758473652127),
 (298, 0.05290092118939488),
 (299, 0.10825317547305485),
 (300, 0.04564354645876385),
 (301, 0.04166666666666668),
 (302, 0.030772872744833184),
 (303, 0.022271770159368702),
 (304, 0.0),
 (305, 0.032274861218395144),
 (306, 0.0790569415042095),
 (307, 0.06950480468569159),
 (308, 0.021053798026662976),
 (309, 0.07654655446197431),
 (310, 0.038575837490522985),
 (311, 0.05103103630798288),
 (312, 0.06711560552140244),
 (313, 0.029462782549439487),
 (314, 0.0909241209316635),
 (315, 0.13878402750067526),
 (316, 0.05103103630798288),
 (317, 0.10825317547305485),
 (318, 0.05499266813300749),
 (319, 0.11322770341445959),
 (320, 0.0),
 (321, 0.06316139407998893),
 (322, 0.04622501635210243),
 (323, 0.0),
 (324, 0.06337242505244779),
 (325, 0.0),
 (326, 0.09682458365518543),
 (327, 0.07654655446197431),
 (328, 0.040824829046386304),
 (329, 0.0),
 (330, 0.02083333333333334),
 (331, 0.11322770341445959),
 (332, 0.12009611535381537),
 (333, 0.15861031714362886),
 (334, 0.02083333333333334),
 (335, 0.07216878364870323),
 (336, 0.0),
 (337, 0.0),
 (338, 0.09759000729485333),
 (339, 0.10206207261596577),
 (340, 0.028306925853614898),
 (341, 0.16081688022566923),
 (342, 0.021053798026662976),
 (343, 0.20016019225635895),
 (344, 0.01712971774568829),
 (345, 0.06933752452815364),
 (346, 0.07319250547113999),
 (347, 0.08247860988423227),
 (348, 0.0),
 (349, 0.1559023911155809),
 (350, 0.0),
 (351, 0.0),
 (352, 0.036369648372665396),
 (353, 0.0),
 (354, 0.07024393586862707),
 (355, 0.11572751247156896),
 (356, 0.036084391824351615),
 (357, 0.07654655446197431),
 (358, 0.02727723627949905),
 (359, 0.15713484026367724),
 (360, 0.06762522260005743),
 (361, 0.13043729868748774),
 (362, 0.021516574145596764),
 (363, 0.10540925533894599),
 (364, 0.0880450906325624),
 (365, 0.07053456158585984),
 (366, 0.0),
 (367, 0.07856742013183862),
 (368, 0.046829290579084706),
 (369, 0.0),
 (370, 0.0),
 (371, 0.0),
 (372, 0.059478868928860826),
 (373, 0.0),
 (374, 0.052704627669472995),
 (375, 0.027777777777777783),
 (376, 0.08564858872844146),
 (377, 0.0),
 (378, 0.03823595564509363),
 (379, 0.0652791209833867),
 (380, 0.0),
 (381, 0.0),
 (382, 0.05455447255899809),
 (383, 0.0),
 (384, 0.05025189076296061),
 (385, 0.0),
 (386, 0.019117977822546817),
 (387, 0.07106690545187015),
 (388, 0.039652579285907215),
 (389, 0.13401406685472436),
 (390, 0.1210455065337605),
 (391, 0.0862581949177943),
 (392, 0.0),
 (393, 0.0),
 (394, 0.14011213457945126),
 (395, 0.030096463271442307),
 (396, 0.07216878364870323),
 (397, 0.15811388300841897),
 (398, 0.14433756729740646),
 (399, 0.0),
 (400, 0.0),
 (401, 0.09622504486493763),
 (402, 0.0),
 (403, 0.0),
 (404, 0.17677669529663692),
 (405, 0.0),
 (406, 0.0),
 (407, 0.06019292654288461),
 (408, 0.0220112726581406),
 (409, 0.028306925853614898),
 (410, 0.023728949893812478),
 (411, 0.023112508176051216),
 (412, 0.0),
 (413, 0.0),
 (414, 0.049507377148833714),
 (415, 0.0440225453162812),
 (416, 0.13153805490049508),
 (417, 0.026802813370944874),
 (418, 0.06299407883487121),
 (419, 0.10067340828210367),
 (420, 0.0),
 (421, 0.0),
 (422, 0.17407765595569785),
 (423, 0.0),
 (424, 0.0),
 (425, 0.06123724356957946),
 (426, 0.0790569415042095),
 (427, 0.10640706634484359),
 (428, 0.1147078669352809),
 (429, 0.0790569415042095),
 (430, 0.07537783614444092),
 (431, 0.048795003647426664),
 (432, 0.013638618139749524),
 (433, 0.0),
 (434, 0.0790569415042095),
 (435, 0.031497039417435604),
 (436, 0.044543540318737404),
 (437, 0.03928371006591931),
 (438, 0.046829290579084706),
 (439, 0.04166666666666668),
 (440, 0.02551551815399144),
 (441, 0.06762522260005743),
 (442, 0.12562972690740154),
 (443, 0.0),
 (444, 0.0),
 (445, 0.028867513459481294),
 (446, 0.0),
 (447, 0.027399831217559553),
 (448, 0.22681617718163874),
 (449, 0.025125945381480306),
 (450, 0.029617443887954623),
 (451, 0.13888888888888892),
 (452, 0.1443375672974065),
 (453, 0.08164965809277261),
 (454, 0.02083333333333334),
 (455, 0.12909944487358058),
 (456, 0.14907119849998599),
 (457, 0.09316949906249124),
 (458, 0.0),
 (459, 0.0),
 (460, 0.0),
 (461, 0.0660338179744218),
 (462, 0.13333333333333333),
 (463, 0.040824829046386304),
 (464, 0.06154574548966637),
 (465, 0.11785113019775795),
 (466, 0.0880450906325624),
 (467, 0.10369516947304254),
 (468, 0.16343011261515333),
 (469, 0.12198750911856666),
 (470, 0.04123930494211613),
 (471, 0.0),
 (472, 0.04564354645876385),
 (473, 0.0),
 (474, 0.09869275424396537),
 (475, 0.026802813370944874),
 (476, 0.09491579957524991),
 (477, 0.10540925533894599),
 (478, 0.08606629658238706),
 (479, 0.0842151921066519),
 (480, 0.0),
 (481, 0.0),
 (482, 0.0),
 (483, 0.0),
 (484, 0.03402069087198859),
 (485, 0.06846531968814579),
 (486, 0.04351941398892446),
 (487, 0.055555555555555566),
 (488, 0.05499266813300749),
 (489, 0.0),
 (490, 0.07647191129018727),
 (491, 0.0),
 (492, 0.0),
 (493, 0.11410886614690963),
 (494, 0.055555555555555566),
 (495, 0.0),
 (496, 0.055555555555555566),
 (497, 0.08040844011283463),
 (498, 0.07654655446197431),
 (499, 0.0660338179744218),
 (500, 0.019117977822546817),
 (501, 0.0),
 (502, 0.036369648372665396),
 (503, 0.1147078669352809),
 (504, 0.040824829046386304),
 (505, 0.06762522260005743),
 (506, 0.026802813370944874),
 (507, 0.052704627669472995),
 (508, 0.04123930494211613),
 (509, 0.06622661785325219),
 (510, 0.06454972243679029),
 (511, 0.032274861218395144),
 (512, 0.044543540318737404),
 (513, 0.0),
 (514, 0.0),
 (515, 0.07118684968143743),
 (516, 0.1041666666666667),
 (517, 0.05773502691896259),
 (518, 0.08333333333333334),
 (519, 0.0),
 (520, 0.0912870929175277),
 (521, 0.0),
 (522, 0.02727723627949905),
 (523, 0.1351474756798972),
 (524, 0.022821773229381927),
 (525, 0.10206207261596575),
 (526, 0.08908708063747481),
 (527, 0.0),
 (528, 0.0),
 (529, 0.0),
 (530, 0.0),
 (531, 0.1844661968431555),
 (532, 0.0),
 (533, 0.18711379979593726),
 (534, 0.040824829046386304),
 (535, 0.06316139407998893),
 (536, 0.029462782549439487),
 (537, 0.15861031714362886),
 (538, 0.08838834764831846),
 (539, 0.1767766952966369),
 (540, 0.030772872744833184),
 (541, 0.0),
 (542, 0.0),
 (543, 0.032274861218395144),
 (544, 0.04622501635210243),
 (545, 0.11135885079684352),
 (546, 0.05360562674188975),
 (547, 0.0),
 (548, 0.039652579285907215),
 (549, 0.0),
 (550, 0.06384423980690615),
 (551, 0.023414645289542353),
 (552, 0.0),
 (553, 0.13638618139749525),
 (554, 0.0993399267798783),
 (555, 0.018791150700070727),
 (556, 0.11895773785772165),
 (557, 0.12247448713915891),
 (558, 0.09231861823449956),
 (559, 0.0),
 (560, 0.0),
 (561, 0.14147911460452758),
 (562, 0.12038585308576923),
 (563, 0.08040844011283463),
 (564, 0.0),
 (565, 0.04166666666666668),
 (566, 0.0),
 (567, 0.09682458365518543),
 (568, 0.022271770159368702),
 (569, 0.0),
 (570, 0.03790490217894517),
 (571, 0.0),
 (572, 0.08018753738744804),
 (573, 0.07426106572325057),
 (574, 0.04351941398892446),
 (575, 0.042562826537937436),
 (576, 0.0),
 (577, 0.0),
 (578, 0.03450327796711772),
 (579, 0.14493772609105074),
 (580, 0.0),
 (581, 0.0),
 (582, 0.0),
 (583, 0.0),
 (584, 0.0),
 (585, 0.03402069087198859),
 (586, 0.0),
 (587, 0.0),
 (588, 0.026802813370944874),
 (589, 0.028867513459481294),
 (590, 0.030096463271442307),
 (591, 0.01689343445998715),
 (592, 0.08703882797784893),
 (593, 0.031497039417435604),
 (594, 0.10580184237878976),
 (595, 0.0),
 (596, 0.09449111825230681),
 (597, 0.0),
 (598, 0.03790490217894517),
 (599, 0.036369648372665396),
 (600, 0.06299407883487121),
 (601, 0.0),
 (602, 0.024056261216234408),
 (603, 0.026352313834736497),
 (604, 0.030096463271442307),
 (605, 0.0),
 (606, 0.052704627669472995),
 (607, 0.06622661785325219),
 (608, 0.0),
 (609, 0.030096463271442307),
 (610, 0.0),
 (611, 0.21128856368212923),
 (612, 0.04841229182759271),
 (613, 0.13638618139749525),
 (614, 0.021516574145596764),
 (615, 0.07118684968143743),
 (616, 0.04351941398892446),
 (617, 0.0),
 (618, 0.10660035817780524),
 (619, 0.0),
 (620, 0.08564858872844146),
 (621, 0.020211302086361082),
 (622, 0.05025189076296061),
 (623, 0.04351941398892446),
 (624, 0.1272937693043289),
 (625, 0.0),
 (626, 0.09820927516479827),
 (627, 0.0),
 (628, 0.0),
 (629, 0.08492077756084469),
 (630, 0.1272937693043289),
 (631, 0.0),
 (632, 0.07118684968143743),
 (633, 0.0),
 (634, 0.059478868928860826),
 (635, 0.023728949893812478),
 (636, 0.10998533626601498),
 (637, 0.0),
 (638, 0.032274861218395144),
 (639, 0.0),
 (640, 0.055555555555555566),
 (641, 0.13623731522826654),
 (642, 0.0),
 (643, 0.0700140042014005),
 (644, 0.0),
 (645, 0.11180339887498948),
 (646, 0.061858957413174195),
 (647, 0.020619652471058066),
 (648, 0.0),
 (649, 0.05544159532159297),
 (650, 0.0),
 (651, 0.0),
 (652, 0.020619652471058066),
 (653, 0.14433756729740646),
 (654, 0.020016019225635895),
 (655, 0.03696106354772865),
 (656, 0.13401406685472436),
 (657, 0.1041666666666667),
 (658, 0.0),
 (659, 0.0),
 (660, 0.0),
 (661, 0.0),
 (662, 0.0),
 (663, 0.14900989016981744),
 (664, 0.022271770159368702),
 (665, 0.10309826235529033),
 (666, 0.03823595564509363),
 (667, 0.03696106354772865),
 (668, 0.09231861823449955),
 (669, 0.07118684968143743),
 (670, 0.0),
 (671, 0.0),
 (672, 0.08333333333333336),
 (673, 0.0950586375786717),
 (674, 0.11825404121991004),
 (675, 0.0912870929175277),
 (676, 0.024397501823713332),
 (677, 0.0),
 (678, 0.07024393586862707),
 (679, 0.058925565098878974),
 (680, 0.020412414523193152),
 (681, 0.06123724356957946),
 (682, 0.0),
 (683, 0.0),
 (684, 0.0),
 (685, 0.026352313834736497),
 (686, 0.14147911460452758),
 (687, 0.0),
 (688, 0.044543540318737404),
 (689, 0.0),
 (690, 0.0),
 (691, 0.0),
 (692, 0.032274861218395144),
 (693, 0.0),
 (694, 0.0),
 (695, 0.025923792368260635),
 (696, 0.07647191129018727),
 (697, 0.024753688574416857),
 (698, 0.042562826537937436),
 (699, 0.0),
 (700, 0.09245003270420486),
 (701, 0.0),
 (702, 0.07580980435789034),
 (703, 0.0),
 (704, 0.018952451089472584),
 (705, 0.0),
 (706, 0.0),
 (707, 0.049507377148833714),
 (708, 0.06019292654288461),
 (709, 0.15990053726670783),
 (710, 0.12500000000000003),
 (711, 0.0),
 (712, 0.017902871850985828),
 (713, 0.0),
 (714, 0.07161148740394331),
 (715, 0.04123930494211613),
 (716, 0.03450327796711772),
 (717, 0.03823595564509363),
 (718, 0.09016696346674324),
 (719, 0.0),
 (720, 0.0),
 (721, 0.147087101353638),
 (722, 0.054126587736527426),
 (723, 0.039652579285907215),
 (724, 0.14900989016981744),
 (725, 0.0660338179744218),
 (726, 0.026802813370944874),
 (727, 0.0),
 (728, 0.1072112534837795),
 (729, 0.06622661785325219),
 (730, 0.09731236802019039),
 (731, 0.09016696346674324),
 (732, 0.023414645289542353),
 (733, 0.0),
 (734, 0.02727723627949905),
 (735, 0.04166666666666668),
 (736, 0.1421338109037403),
 (737, 0.04564354645876385),
 (738, 0.06154574548966637),
 (739, 0.032274861218395144),
 (740, 0.0),
 (741, 0.047457899787624956),
 (742, 0.021053798026662976),
 (743, 0.04210759605332595),
 (744, 0.23185650837574195),
 (745, 0.02083333333333334),
 (746, 0.024753688574416857),
 (747, 0.04123930494211613),
 (748, 0.15309310892394865),
 (749, 0.0),
 (750, 0.018791150700070727),
 (751, 0.03500700210070025),
 (752, 0.04351941398892446),
 (753, 0.0),
 (754, 0.09028938981432692),
 (755, 0.13153805490049508),
 (756, 0.0842151921066519),
 (757, 0.0),
 (758, 0.017010345435994296),
 (759, 0.0790569415042095),
 (760, 0.05590169943749475),
 (761, 0.04564354645876385),
 (762, 0.05773502691896259),
 (763, 0.15843106263111947),
 (764, 0.13176156917368248),
 (765, 0.14433756729740646),
 (766, 0.08006407690254358),
 (767, 0.04351941398892446),
 (768, 0.031497039417435604),
 (769, 0.1684303842133038),
 (770, 0.12961896184130317),
 (771, 0.0),
 (772, 0.06123724356957946),
 (773, 0.0),
 (774, 0.13878402750067526),
 (775, 0.04351941398892446),
 (776, 0.031497039417435604),
 (777, 0.1721325931647741),
 (778, 0.08617274844321393),
 (779, 0.035533452725935076),
 (780, 0.07856742013183862),
 (781, 0.0),
 (782, 0.09016696346674324),
 (783, 0.12028130608117205),
 (784, 0.04508348173337162),
 (785, 0.048795003647426664),
 (786, 0.08606629658238706),
 (787, 0.10825317547305485),
 (788, 0.09365858115816941),
 (789, 0.031497039417435604),
 (790, 0.0),
 (791, 0.08512565307587487),
 (792, 0.022821773229381927),
 (793, 0.08908708063747481),
 (794, 0.13693063937629157),
 (795, 0.0),
 (796, 0.07319250547113999),
 (797, 0.0),
 (798, 0.148969892882781),
 (799, 0.0),
 (800, 0.05025189076296061),
 (801, 0.13801311186847087),
 (802, 0.10660035817780524),
 (803, 0.18093671611393652),
 (804, 0.02727723627949905),
 (805, 0.0),
 (806, 0.05103103630798288),
 (807, 0.07273929674533079),
 (808, 0.052510503151050374),

In [41]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:5]

[(837, 0.2727723627949905),
 (18544, 0.26655699499159163),
 (2151, 0.2611164839335468),
 (4075, 0.26020824993326663)]

In [42]:
df[df["title"]=='Avatar'].index[0]

3

In [45]:
def recommend(movie):
    movie_index=df[df['title']==movie].index[0]
    distance=similarity[movie_index]
    movie_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:5]
    for i in movie_list:
        print(df.iloc[i[0]].title)

In [48]:
recommend('Avatar')

Ikarie XB 1
Skylines
King Shakir Recycle
Aliens in the Attic

In [ ]:
import pickle